/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/boloacetato.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/boloacetato.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bolo1.geometry} material={materials.bolo1} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
      <mesh geometry={nodes.recheio.geometry} material={materials.recheio1} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
      <mesh geometry={nodes.Base_Cake.geometry} material={materials.Default} rotation={[Math.PI / 2, 0, 0]} scale={3.261} />
      <mesh geometry={nodes.Chantili.geometry} material={materials.Chantili} rotation={[Math.PI / 2, 0, 0]} scale={[6.315, 6.315, 9.383]} />
      <mesh geometry={nodes.chantili.geometry} material={materials.Chantili} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.plastico.geometry} material={materials.plastico} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
      <mesh geometry={nodes.recheio001.geometry} material={materials.recheio2} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
      <mesh geometry={nodes.bolo1002.geometry} material={materials.bolo3} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
      <mesh geometry={nodes.bolo1003.geometry} material={materials.bolo2} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
    </group>
  )
}

useGLTF.preload('/boloacetato.glb')
