/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/bolonew.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bolonew.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bolo1.geometry} material={materials.bolo1} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
      <mesh geometry={nodes.cobertura.geometry} material={materials.cobertura} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 6.844]} />
      <mesh geometry={nodes.recheio.geometry} material={materials.recheio} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
      <mesh geometry={nodes.strawberry.geometry} material={materials.Strawberry} rotation={[0.311, 0, Math.PI / 2]} scale={0.008} />
      <mesh geometry={nodes.strawberry001.geometry} material={materials.Strawberry} rotation={[2.831, -0.006, -1.573]} scale={0.008} />
      <mesh geometry={nodes.strawberry002.geometry} material={materials.Strawberry} rotation={[1.502, -1.259, 3.07]} scale={0.008} />
      <mesh geometry={nodes.strawberry003.geometry} material={materials.Strawberry} rotation={[1.658, 1.259, -0.092]} scale={0.008} />
      <mesh geometry={nodes.strawberry004.geometry} material={materials.Strawberry} rotation={[2.723, -0.719, -1.856]} scale={0.008} />
      <mesh geometry={nodes.strawberry005.geometry} material={materials.Strawberry} rotation={[0.421, 0.725, 1.282]} scale={0.008} />
      <mesh geometry={nodes.strawberry006.geometry} material={materials.Strawberry} rotation={[2.708, 0.757, -1.263]} scale={0.008} />
      <mesh geometry={nodes.strawberry007.geometry} material={materials.Strawberry} rotation={[0.432, -0.751, 1.875]} scale={0.008} />
      <mesh geometry={nodes.BRIGADEIRO.geometry} material={materials.brigaderio} scale={0.057} />
      <mesh geometry={nodes.BRIGADEIRO001.geometry} material={materials.brigaderio} scale={0.059} />
      <mesh geometry={nodes.BRIGADEIRO002.geometry} material={materials.brigaderio} scale={0.055} />
      <mesh geometry={nodes.BRIGADEIRO003.geometry} material={materials.brigaderio} scale={0.051} />
      <mesh geometry={nodes.BRIGADEIRO004.geometry} material={materials.brigaderio} scale={0.057} />
      <mesh geometry={nodes.BRIGADEIRO005.geometry} material={materials.brigaderio} scale={0.049} />
      <mesh geometry={nodes.bolo2.geometry} material={materials.bolo1} rotation={[Math.PI / 2, 0, 0]} scale={[5.162, 5.162, 9.85]} />
      <mesh geometry={nodes.cobertura001.geometry} material={materials.cobertura} rotation={[Math.PI / 2, 0, -0.824]} scale={[5.162, 5.162, 5.613]} />
      <mesh geometry={nodes.recheio001.geometry} material={materials.recheio} rotation={[Math.PI / 2, 0, 0]} scale={[5.162, 5.162, 9.85]} />
      <mesh geometry={nodes.strawberry2.geometry} material={materials.Strawberry} rotation={[2.921, -0.135, -1.603]} scale={0.009} />
      <mesh geometry={nodes.strawberry2001.geometry} material={materials.Strawberry} rotation={[1.658, 1.259, -0.092]} scale={0.009} />
      <mesh geometry={nodes.strawberry2003.geometry} material={materials.Strawberry} rotation={[2.723, -0.719, -1.856]} scale={0.009} />
      <mesh geometry={nodes.strawberry2002.geometry} material={materials.Strawberry} rotation={[2.708, 0.757, -1.263]} scale={0.009} />
      <mesh geometry={nodes.BRIGADEIRO2001.geometry} material={materials.brigaderio} scale={0.059} />
      <mesh geometry={nodes.BRIGADEIRO2.geometry} material={materials.brigaderio} scale={0.059} />
      <mesh geometry={nodes.BRIGADEIRO2002.geometry} material={materials.brigaderio} scale={0.059} />
      <mesh geometry={nodes.Base_Cake.geometry} material={materials.Default} rotation={[Math.PI / 2, 0, 0]} scale={3.261} />
    </group>
  )
}

useGLTF.preload('/bolonew.glb')
