/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/bolochantininhobase.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CakeChantininho(props) {
  const { nodes, materials } = useGLTF('/bolochantininhobase.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base_Cake001.geometry} material={materials['Default.001']} rotation={[Math.PI / 2, 0, 0]} scale={3.261} />
      <mesh geometry={nodes.bolo1001.geometry} material={materials.cakechantininho1} position={[0.003, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[6.294, 6.294, 12.011]} />
      <mesh geometry={nodes.chantili001.geometry} material={materials['Chantili.002']} position={[0.003, -0.03, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/bolochantininhobase.glb')
