/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/slicecakeacetato.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/slicecakeacetato.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cobertura1001.geometry} material={materials['Material.003']} position={[0, -0.023, -0.019]} scale={[0.416, 0.339, 0.416]} />
      <mesh geometry={nodes.bolobase001.geometry} material={materials['bolo1.001']} position={[0, 0.26, 0]} scale={[0.416, 0.298, 0.416]} />
      <mesh geometry={nodes.bolobase002.geometry} material={materials['Material.001']} position={[0, 0.26, 0]} scale={[0.416, 0.298, 0.416]} />
      <mesh geometry={nodes.bolobase003.geometry} material={materials['bolo1.001']} position={[0, 0.26, 0]} scale={[0.416, 0.298, 0.416]} />
      <mesh geometry={nodes.bolobase004.geometry} material={materials['bolo3.001']} position={[0, 0.26, 0]} scale={[0.416, 0.298, 0.416]} />
    </group>
  )
}

useGLTF.preload('/slicecakeacetato.glb')
