/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/slicecake.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SliceCakechant(props) {
  const { nodes, materials } = useGLTF('/slicecake.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.bolo1} position={[0, 0.26, 0]} scale={[0.416, 0.298, 0.416]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.011']} position={[0, 0.26, -0.019]} scale={[0.416, 0.298, 0.416]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.bolo3} position={[0, 0.26, 0]} scale={[0.416, 0.298, 0.416]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.011']} position={[0, -0.023, -0.019]} scale={[0.416, 0.339, 0.416]} />
    </group>
  )
}

useGLTF.preload('/slicecake.glb')
